# Generated by Django 4.2.2 on 2023-06-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('solicitud', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('aceptado', models.BooleanField(default=False)),
                ('fecha_aceptado', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
